//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Scripts/Input/PlayerInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInput : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInput"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""8e11cde3-787b-4fd1-a282-ffdc5d7ead5a"",
            ""actions"": [
                {
                    ""name"": ""CreateTower"",
                    ""type"": ""Button"",
                    ""id"": ""fad9102a-3d6f-4d31-aca0-a0eddab30374"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GetPreesLeftMouseButton"",
                    ""type"": ""Button"",
                    ""id"": ""4abbc2ed-a12e-475f-85c8-1a395820ee24"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""8ebaff87-cee1-46ca-984e-9aba97dfa8f5"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse"",
                    ""action"": ""CreateTower"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9c71d88c-afc5-47a7-b366-6e059dc0f08a"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse"",
                    ""action"": ""GetPreesLeftMouseButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Mouse"",
            ""bindingGroup"": ""Mouse"",
            ""devices"": [
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_CreateTower = m_Player.FindAction("CreateTower", throwIfNotFound: true);
        m_Player_GetPreesLeftMouseButton = m_Player.FindAction("GetPreesLeftMouseButton", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private IPlayerActions m_PlayerActionsCallbackInterface;
    private readonly InputAction m_Player_CreateTower;
    private readonly InputAction m_Player_GetPreesLeftMouseButton;
    public struct PlayerActions
    {
        private @PlayerInput m_Wrapper;
        public PlayerActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @CreateTower => m_Wrapper.m_Player_CreateTower;
        public InputAction @GetPreesLeftMouseButton => m_Wrapper.m_Player_GetPreesLeftMouseButton;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterface != null)
            {
                @CreateTower.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCreateTower;
                @CreateTower.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCreateTower;
                @CreateTower.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCreateTower;
                @GetPreesLeftMouseButton.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnGetPreesLeftMouseButton;
                @GetPreesLeftMouseButton.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnGetPreesLeftMouseButton;
                @GetPreesLeftMouseButton.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnGetPreesLeftMouseButton;
            }
            m_Wrapper.m_PlayerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @CreateTower.started += instance.OnCreateTower;
                @CreateTower.performed += instance.OnCreateTower;
                @CreateTower.canceled += instance.OnCreateTower;
                @GetPreesLeftMouseButton.started += instance.OnGetPreesLeftMouseButton;
                @GetPreesLeftMouseButton.performed += instance.OnGetPreesLeftMouseButton;
                @GetPreesLeftMouseButton.canceled += instance.OnGetPreesLeftMouseButton;
            }
        }
    }
    public PlayerActions @Player => new PlayerActions(this);
    private int m_MouseSchemeIndex = -1;
    public InputControlScheme MouseScheme
    {
        get
        {
            if (m_MouseSchemeIndex == -1) m_MouseSchemeIndex = asset.FindControlSchemeIndex("Mouse");
            return asset.controlSchemes[m_MouseSchemeIndex];
        }
    }
    public interface IPlayerActions
    {
        void OnCreateTower(InputAction.CallbackContext context);
        void OnGetPreesLeftMouseButton(InputAction.CallbackContext context);
    }
}
